-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: no-commit-to-branch
        args: ['--pattern', '^(?!((fix|feat)\/[a-zA-Z0-9\-]+)$).*']
    # -   id: ...
