name: 'Assert Branch Naming Convention'
on: 
  pull_request_target:
     types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^DMS-*' # Regex the branch should match. This example enforces grouping
          min_length: 3 # Min length of the branch name
          max_length: 20 # Max length of the branch name
