name: Manualtrigger2

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
  schedule:
    - cron: '50 5 * * 4'      
        

jobs:
    hello:
        runs-on: windows-latest

        steps:
        - name: Echo Hello
          run:  java -version
