name: Manualtrigger2

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        

jobs:
    hello:
        runs-on: windows-latest
        permissions: write-all

        steps:
        - name: Echo Hello
          run:  java -version
