name: Manualtrigger2

on:
  schedule:
    - cron: '30 5 * * 4'
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        

jobs:
    hello:
        runs-on: windows-latest

        steps:
        - name: Echo Hello
          run:  java -version
