name: Enforce

on:
  pull_request:
   types:
   - opened
   - synchronize

jobs:
  enforce-pr-naming:
   runs-on: ubuntu-latest
 
   steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v1
        with:
          # Match pull request titles in the form UI-1234 - Message.
          pattern: '^NSE-\d* - '
        
 
