name: Enforce

on:
  pull_request:
   types:
   - opened
   - synchronize

jobs:
  enforce-pr-naming:
   runs-on: ubuntu-latest
 
   steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          # Match pull request titles in the form UI-1234 - Message.
          regex: '^NSE-\d* - '
      
        
 
