name: Enforce

on:
  pull_request:
   types:
   - opened
   - synchronize

jobs:
  enforce-pr-naming:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify PR name
      run: |
        pr_title=$(git log --format=%s -n 1 ${{ github.event.pull_request.head.sha }})
        pattern="^NSE-.*"
        if [[ ! $pr_title =~ $pattern ]]; then
        echo "Invalid PR name. Please follow the naming pattern: YOUR_DESIRED_PATTERN"
        exit 1
       
 
